apiVersion: v2
name: 4g3n7-desktop
description: A Helm chart for 4G3N7 Desktop service
type: application
version: 0.1.0
appVersion: "edge"
keywords:
  - 4g3n7
  - desktop
  - vnc
  - remote-desktop
maintainers:
  - name: 4G3N7 Team
sources:
  - https://github.com/4g3n7-ai/4g3n7