apiVersion: v2
name: 4g3n7-agent
description: A Helm chart for 4G3N7 Agent service
type: application
version: 0.1.0
appVersion: "edge"
dependencies:
  - name: postgresql
    version: "~13.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
keywords:
  - 4g3n7
  - agent
  - api
maintainers:
  - name: 4G3N7 Team
sources:
  - https://github.com/4g3n7-ai/4g3n7